[package]
name = "ggh"
version = "0.1.0"
edition = "2024"

[dependencies]
xshell = "0.2.7"
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
